# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 纯粹
subtitle: '风卷过的起点'
description: '爱美食/纪录片/夜猫子'
keywords: [班班, Leirock, Hexo, blog, 博客, 经济学, economics]
author: 班班
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://blog.dlzhang.com
root: /
permalink: /post/:pid/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: timeline
category_dir: ''
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 404.html

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: true
  tab_replace: true
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: life
category_map:
  碎碎念: life
  观察者: viewpoint
  笔记本: note
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Minifier & Optimization plugin
## See: https://github.com/chenzhutian/hexo-all-minifier
all_minifier: true
html_minifier:
  silent: true
css_minifier:
  silent: true
js_minifier:
  silent: true
image_minifier:
  enable: false

# Hexo Server
server:
  port: 4000
  ip: 127.0.0.1

# Waline
# For more information: https://waline.js.org
waline:
  enable: true
  libUrl: https://lib.baomitu.com/waline/latest/Waline.min.js
  serverURL: https://waline.dlzhang.com # Waline server address url
  avatar: '' # Gravatar style
  login: disable
  meta: [nick, mail, link] # Custom comment header
  requiredMeta: [nick, mail] # Set required fields: [nick] | [nick, mail]
  pageSize: 5 # Pagination size
  visitor: false # Article reading statistic
  comment_count: true  # If false, comment count will only be displayed in post page, not in home page
  copyright: false
  dark: auto
  emoji:  [
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/weibo',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tw-emoji',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/qq',
  ]
  locale:
    placeholder: 在这里分享你的观点与想法，评论通过审核后才会显示。昵称、邮箱必填，回复通过邮件提醒。 # Comment box placeholder
    admin: 博主
    nick: 昵称*
    mail: 邮箱*
    link: 网址
    #login: 管理

# hexo-renderer-markdown-it
# For more information: https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration
markdown:
  langPrefix: 'language-'
  plugins:
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup

#########################
##### 以下插件设置停用 #####
#########################

# hexo-extend-theme
# Replace any theme file in layout folder to a custom file.
# For more information: https://github.com/jiangtj/hexo-extend-theme
theme_plus:
  views:
    - path: 'page.njk'
      file: 'custom/page.njk'
    - path: 'archive.njk'
      file: 'custom/archive.njk'

# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See: https://theme-next.js.org/docs/theme-settings/
# ---------------------------------------------------------------

theme_config:

  # Remove unnecessary files after hexo generate.
  minify: true

  # Define custom file paths.
  # Create your custom files in site directory `source/_data` and uncomment needed files below.
  custom_file_path:
    head: source/_data/head.njk
    #header: source/_data/header.njk
    #sidebar: source/_data/sidebar.njk
    postMeta: source/_data/post-meta.njk
    postBodyEnd: source/_data/post-body-end.njk
    #footer: source/_data/footer.njk
    bodyEnd: source/_data/body-end.njk
    variable: source/_data/variables.styl
    mixin: source/_data/mixins.styl
    style: source/_data/styles.styl

  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  scheme: Gemini
  darkmode: true
  # Color style: Day of Mourning
  gray: false

  # ---------------------------------------------------------------
  # Site Information Settings
  # ---------------------------------------------------------------

  favicon:
    small: ''
    medium: /resources/favicon/favicon-32.png
    apple_touch_icon: /resources/favicon/apple-touch-icon.png
    safari_pinned_tab: ''
    android_manifest: ''

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  menu:
    life: /life/ || fas fa-pizza-slice
    viewpoint: /viewpoint/ || fas fa-eye
    note: /note/ || fas fa-pencil-alt
    tags: /tags/ || fas fa-tags
    guestbook: 
      default: /guestbook/ || fas fa-location-arrow
      friends: ../friends/ || fas fa-link
      history: ../post/26/ || fas fa-history
  #  overview: 
  #    default: /overview/ || fas fa-archive
  #    timeline: timeline/ || fas fa-history

  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.js.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------

  # Sidebar Avatar
  avatar:
    url: https://sdn.geekzu.org/avatar/cc763511474fe24ffcc80257fb7cb970?s=128
    rounded: true

  # Posts / Categories / Tags in sidebar.
  site_state: false

  social:
    微博: https://weibo.com/leirock || fab fa-weibo
    GitHub: https://github.com/leirock || fab fa-github
    RSS: /atom.xml || fas fa-rss

  social_icons:
    icons_only: true

  toc:
    # Automatically add list number to toc.
    number: false
    max_depth: 3 # <h3> ###

  # ---------------------------------------------------------------
  # Footer Settings
  # See: https://theme-next.js.org/docs/theme-settings/footer
  # ---------------------------------------------------------------

  footer:
    since: 2008

    # Icon between year and copyright info.
    icon:
      name: fas fa-heart
      animated: true
      color: "#f06292"

    copyright: 纯粹

    # Powered by Hexo & NexT
    powered: true

  # ---------------------------------------------------------------
  # Post Settings
  # See: https://theme-next.js.org/docs/theme-settings/posts
  # ---------------------------------------------------------------

  # Read more button
  read_more_btn: false

  # Post meta display settings
  post_meta:
    item_text: false
    updated_at:
      enable: false

  # Post wordcount display settings
  # Dependencies: https://github.com/next-theme/hexo-word-counter
  symbols_count_time:
    separated_meta: false

  # Show previous post and next post in post footer if exists
  # Available values: left | right | false
  post_navigation: right

  # ---------------------------------------------------------------
  # Misc Theme Settings
  # See: https://theme-next.js.org/docs/theme-settings/miscellaneous
  # ---------------------------------------------------------------

  # Preconnect CDN for fonts and plugins.
  preconnect: true

  # Browser header panel color.
  theme_color:
    light: "#e7ddc8"
    dark: "#181c27"

  codeblock:
    # All available themes: https://theme-next.js.org/highlight/
    prism:
      light: prism
      dark: prism-okaidia
    copy_button:
      enable: true
      style: flat

  back2top:
    scrollpercent: true

  # ---------------------------------------------------------------
  # Font Settings
  # ---------------------------------------------------------------

  font:
    enable: true
    global:
      external: false
      family: LXGW  # EB Garamond, Noto Serif SC
    title:
      external: false
      family: Long Cang
      size: 2.2
    headings:
      size: 1.6
    codes:
      external: false
      family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace

  # ---------------------------------------------------------------
  # SEO Settings
  # See: https://theme-next.js.org/docs/theme-settings/seo
  # ---------------------------------------------------------------

  baidu_site_verification: wvc37nzEad

  # ---------------------------------------------------------------
  # Third Party Plugins & Services Settings
  # See: https://theme-next.js.org/docs/third-party-services/
  # ---------------------------------------------------------------

  math:
    mathjax:
      enable: true
  pjax: true
  fancybox: true
  lazyload: true
  pangu: true

  # ---------------------------------------------------------------
  # Search Services
  # See: https://theme-next.js.org/docs/third-party-services/search-services
  # ---------------------------------------------------------------

  # Dependencies: https://github.com/next-theme/hexo-generator-searchdb
  local_search:
    enable: true

  # ---------------------------------------------------------------
  # Tags Settings
  # See: https://theme-next.js.org/docs/tag-plugins/
  # ---------------------------------------------------------------

  # Note tag (bootstrap callout)
  note:
    # Note tag style values:
    #  - simple    bootstrap callout old alert style. Default.
    #  - modern    bootstrap callout new (v2-v3) alert style.
    #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
    #  - disabled  disable all CSS styles import of note tag.
    style: flat
    icons: true
    # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
    # Offset also applied to label tag variables. This option can work with disabled note tag.
    light_bg_offset: 0

  # Tabs tag
  tabs:
    sticky: true
    transition:
      tabs: true
      labels: true

  # ---------------------------------------------------------------
  # Animation Settings
  # ---------------------------------------------------------------

  motion:
    enable: false

  # ---------------------------------------------------------------
  # CDN Settings
  # See: https://theme-next.js.org/docs/advanced-settings/vendors
  # ---------------------------------------------------------------

  vendors:
    # The CDN provider of NexT internal scripts.
    internal: custom
    plugins: custom
    # custom_cdn_url: https://lib.baomitu.com/${cdnjs_name}/${version}/${cdnjs_file} #360 75CDN
    # custom_cdn_url: https://code.bdstatic.com/npm/${npm_name}@${version}/${npm_file} #百度云
    # custom_cdn_url: https://unpkg.zhimg.com/${npm_name}@${version}/${npm_file} #知乎
    custom_cdn_url: https://npm.elemecdn.com/${npm_name}@${version}/${npm_file} #饿了么

  # Assets
  # css - local
  # js - same as internal CDN
  images: /resources/img/ # root /img/ folder