# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 频率
subtitle: 风卷过的起点
description: 爱美食/看展览/夜猫子
keywords: [blog, 博客, pinlyu, 频率, Dylan Zhang]
author: 班班
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://pinlyu.com
root: /
permalink: /posts/:pid/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: timeline
category_dir: ''
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 404.html

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# Syntax highlight
## https://hexo.io/zh-cn/docs/syntax-highlight
syntax_highlighter: prismjs #highlight.js
highlight:
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  exclude_languages:
    - example
  wrap: true
  hljs: false
## https://prismjs.com/download.html
prismjs:
  preprocess: true
  line_number: false
  line_threshold: 0
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: life
category_map:
  生活: life
  观点: observer
  笔记: notes
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'empty' # do not use file modified time as updated time

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Minifier & Optimization plugin
## See: https://github.com/chenzhutian/hexo-all-minifier
html_minifier:
  silent: true
css_minifier:
  silent: true
js_minifier:
  silent: true
image_minifier:
  enable: false

# hexo-renderer-marked
## https://github.com/hexojs/hexo-renderer-marked
marked:
  figcaption: true

# 灰色滤镜
gray_filter: false

# 对象存储存储桶自定义域名
cos_domain: https://cdn.pinlyu.com

# Artalk
## Config: https://artalk.js.org
## Plugin: https://github.com/leirock/hexo-next-artalk
artalk:
  enable: true
  server: https://comment.pinlyu.com
  jsUrl: https://comment.pinlyu.com/dist/Artalk.js
  cssUrl: https://comment.pinlyu.com/dist/Artalk.css
  site: 频率
  commentCount: true
  pvCount: false
  darkMode: auto
  useBackendConf: true
