#################################################################
###################### NexT Configuration #######################
#################################################################
# See: https://theme-next.js.org/docs/

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

# Remove unnecessary files after hexo generate.
minify: true

custom_file_path:
  head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  postBodyEnd: source/_data/post-body-end.njk
  footer: source/_data/footer.njk
  bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  mixin: source/_data/mixins.styl
  style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

scheme: Gemini
darkmode: true


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

favicon:
  small: /resources/favicon/favicon.ico
  medium: /resources/favicon/favicon-32.png
  apple_touch_icon: /resources/favicon/apple-touch-icon.png
  safari_pinned_tab: ''
  android_manifest: ''


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  life: /life/ || fas fa-pizza-slice
  observer: /observer/ || fas fa-eye
  notes: /notes/ || fas fa-book
  arts: /arts/ || fas fa-guitar
  album: /album/ || fas fa-camera-retro
  guestbook: /guestbook/ || fas fa-splotch
  #  default: /guestbook/ || fas fa-splotch
  #  links: ../links/ || fas fa-link


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

avatar:
  url: /resources/img/avatar.webp
  rounded: true

site_state: false

social:
  微博: https://dlzhang.com/weibo || fa-brands fa-weibo
  哔哩哔哩: https://dlzhang.com/bilibili || fa-brands fa-bilibili
  RSS: /atom.xml || fas fa-rss

social_icons:
  icons_only: true

toc:
  number: false
  wrap: true # 超出范围文字是否换行
  max_depth: 3 # <h3> ###
  expand_all: true


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2017
  icon:
    name: fas fa-heart
    animated: true
    color: "#f06292"
  copyright: 频率
  powered: false


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

read_more_btn: false

post_meta:
  item_text: false
  updated_at:
    enable: false

tag_icon: true

# Show previous post and next post in post footer if exists
post_navigation: right


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

preconnect: false

theme_color:
  light: "#e7ddc8"
  dark: "#181c27"

codeblock:
  # All available themes: https://theme-next.js.org/highlight/
  #prism:
  #  light: prism
  #  dark: prism-okaidia
  copy_button:
    enable: true
    style: flat
  fold:
    enable: true
    height: 500

back2top:
  scrollpercent: true


# ============================================================= #
# ======================= Font Settings ======================= #
# ============================================================= #

font:
  enable: true
  global:
    external: false
    # 在 head.njk 中设置字体链接  LXGWWenKaiLite, EB Garamond, Noto Serif SC
    family: LXGW WenKai Screen 
  title:
    external: false
    family: Long Cang
    size: 2.2
  headings:
    external: false
    size: 1.6
  codes:
    external: false
    family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace


# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

# Math Formulas Render Support
# See: https://theme-next.js.org/docs/third-party-services/math-equations
math:
  mathjax:
    enable: true
    tags: ams
pjax: true
fancybox: true
lazyload: true
pangu: true

# Umami Analytics
# See: https://umami.is/
umami:
  enable: true
  script_url: https://stats.pinlyu.com/script.js
  website_id: dfd4ef79-619d-4b55-b84e-981fd43cefa9
  data_host_url: # <your umami script CDN url> https://github.com/umami-software/umami/issues/95

# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: false


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

# Note tag (bootstrap callout)
note:
  style: flat
  icons: true
  light_bg_offset: 0

# Tabs tag
tabs:
  sticky: true
  transition:
    tabs: true
    labels: true


# ============================================================= #
# ==================== Animation Services ===================== #
# ============================================================= #

motion:
  enable: false


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #
# See: https://theme-next.js.org/docs/advanced-settings/vendors

vendors:
  # local | jsdelivr | unpkg | cdnjs | custom
  internal: local
  plugins: custom
  custom_cdn_url: https://cdn.staticfile.net/${cdnjs_name}/${version}/${cdnjs_file} #七牛云
  #custom_cdn_url: https://cdn.jsdelivr.net/npm/${npm_name}@${version}/${minified} #jsdelivr


# Assets
# css - local
# js - only valid when vendors.internal is local
images: /resources/img/ # root /img/ folder