# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 醉里挑灯赏猫
subtitle: 班班的碎碎念
description: '阅读/美食/夜猫子/轻音乐/美剧/纪录片/文明VI / Steam'
keywords: [班班, 醉里挑灯赏猫, 博客, blog]
author: 班班
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://blog.dlzhang.com
root: /
permalink: /posts/:pid/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: overview/tags
archive_dir: overview/timeline
category_dir: overview
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - 404.html
  - js/**
  - live2d/**

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: true
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: 碎碎念
category_map:
  学术向: academic
  碎碎念: life
  观察者: viewpoint
  科技树: tech
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Minifier & Optimization plugin
## See: https://github.com/chenzhutian/hexo-all-minifier
all_minifier: true
html_minifier:
  silent: true
css_minifier:
  silent: true
js_minifier:
  silent: true
image_minifier:
  enable: false

# Hexo Server
server:
  port: 4000
  ip: 127.0.0.1

# MiniValine Comment
# See: https://minivaline.js.org/docs/cn/
minivaline:
  enable: true
  mode: xCss # DesertsP or xCss
  placeholder: 欢迎留下你的评论～ # Comment box placeholder
  maxNest: 4 # Sub-comment maximum nesting depth.
  pageSize: 6 # Pagination size.
  lazyload: true
  barrager: false # Comment barrage.
  visitor: false # Visit statistics
  closeUA: true # Turn off UA detection.
  dark: true # Dark mode
  backend: waline
  serverURLs: https://waline.dlzhang.com # Waline server url
  tagMeta: ["管理员", "小伙伴", "访客"] # The String Array of Words to show Flag (only three)
  master:  # The MD5 String Array of master Email to show master Flag.
    - cc763511474fe24ffcc80257fb7cb970
  friends: [] # The MD5 String Array of friends Email to show friends Flag.
  # MiniValine's display language depends on user's browser or system environment
  # Available values: en  | zh-CN | (and many more)
  lang: zh-CN
  cdn: https://cdn.jsdelivr.net/npm/minivaline/dist/MiniValine.min.js
  # Expression Url.
  # https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-customize-emoticons
  emoticonUrl:
    - https://cdn.jsdelivr.net/npm/alus@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/qq@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/Bilibilis@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/tieba@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/twemoji@latest
    - https://cdn.jsdelivr.net/gh/MiniValine/weibo@latest