# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See: https://theme-next.js.org/docs/theme-settings/
# ---------------------------------------------------------------

# Remove unnecessary files after hexo generate.
minify: true

# Define custom file paths.
# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  postBodyEnd: source/_data/post-body-end.njk
  #footer: source/_data/footer.njk
  bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  mixin: source/_data/mixins.styl
  style: source/_data/styles.styl

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

scheme: Gemini
darkmode: true
# Color style: Day of Mourning
gray: false

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || fas fa-home
  overview: 
    default: /overview/ || fas fa-th
    tags: tags/ || fas fa-tags
    timeline: timeline/ || fas fa-archive
  photos: /photos/ || fas fa-camera-retro
  more:
    default: /more/ || fas fa-location-arrow
    book: book/ || fas fa-book
    documentary: documentary/ || fas fa-video
    code: code/ || fas fa-flask
    friends: friends/ || fas fa-heart

# ---------------------------------------------------------------
# Sidebar Settings
# See: https://theme-next.js.org/docs/theme-settings/sidebar
# ---------------------------------------------------------------

# Sidebar Avatar
avatar:
  url: https://cdn.v2ex.com/gravatar/cc763511474fe24ffcc80257fb7cb970?s=200
  rounded: true

# Posts / Categories / Tags in sidebar.
site_state: false

social:
  微博: https://weibo.com/7216640993 || fab fa-weibo
  GitHub: https://github.com/lei2rock || fab fa-github
  RSS: /atom.xml || fas fa-rss

social_icons:
  icons_only: true

toc:
  # Automatically add list number to toc.
  number: false

# ---------------------------------------------------------------
# Footer Settings
# See: https://theme-next.js.org/docs/theme-settings/footer
# ---------------------------------------------------------------

footer:
  since: 2015

  # Icon between year and copyright info.
  icon:
    name: fas fa-heart
    animated: true
    color: "#f06292"

  # Powered by Hexo & NexT
  powered: false

# ---------------------------------------------------------------
# Post Settings
# See: https://theme-next.js.org/docs/theme-settings/posts
# ---------------------------------------------------------------

# Read more button
read_more_btn: false

# Post meta display settings
post_meta:
  updated_at:
    enable: false

# Use icon instead of the symbol # to indicate the tag at the bottom of the post
tag_icon: true

# Related popular posts
# Dependencies: https://github.com/tea3/hexo-related-popular-posts
related_posts:
  enable: true
  title: 相关推荐 # Custom header, leave empty to use the default one

# ---------------------------------------------------------------
# Misc Theme Settings
# See: https://theme-next.js.org/docs/theme-settings/miscellaneous
# ---------------------------------------------------------------

# Preconnect CDN for fonts and plugins.
preconnect: true

# Android Chrome header panel color ($brand-bg / $headband-bg => $black-deep).
android_chrome_color: "#6c599f"

codeblock:
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: tomorrow
    dark: tomorrow-night
  copy_button:
    enable: true
    style: mac

back2top:
  scrollpercent: true

# ---------------------------------------------------------------
# Font Settings
# ---------------------------------------------------------------

font:
  enable: true
  global:
    family: EB Garamond, Noto Serif SC
  title:
    family: Long Cang
    size: 2
  headings:
    size: 1.48

# ---------------------------------------------------------------
# SEO Settings
# See: https://theme-next.js.org/docs/theme-settings/seo
# ---------------------------------------------------------------

disable_baidu_transformation: true
google_site_verification: SJUudYL5q_atXSgew2qwy69FXOnSnNB2rAmwHmcBT9U
baidu_site_verification: wvc37nzEad

# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# See: https://theme-next.js.org/docs/third-party-services/
# ---------------------------------------------------------------

math:
  mathjax:
    enable: true
pjax: true
fancybox: true
lazyload: true
pangu: true

# ---------------------------------------------------------------
# Comments Settings
# See: https://theme-next.js.org/docs/third-party-services/comments
# ---------------------------------------------------------------

# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  enable: true
  appId: ydaoV9samWgzerLX7OHEbRgk-MdYXbMMI # Your leancloud application appid
  appKey: 5jRfX3rExENmJqhdzkRqPndP # Your leancloud application appkey
  serverURLs: # When the custom domain name is enabled, fill it in here
  placeholder: 来这里留下你的想法与观点，邮件通知回复～（昵称中输入 QQ 号可读取 QQ 昵称和邮箱） # Comment box placeholder
  avatar: wavatar # Gravatar style
  meta: [nick, mail, link] # Custom comment header
  pageSize: 10 # Pagination size
  lang: zh-cn # Language, available values: en, zh-cn
  visitor: true # Article reading statistic
  comment_count: true # If false, comment count will only be displayed in post page, not in home page
  recordIP: true # Whether to record the commenter IP
  enableQQ: true # Whether to enable the Nickname box to automatically get QQ Nickname and QQ Avatar
  requiredFields: [mail] # Set required fields: [nick] | [nick, mail]

# ---------------------------------------------------------------
# Statistics and Analytics
# See: https://theme-next.js.org/docs/third-party-services/statistics-and-analytics
# ---------------------------------------------------------------

google_analytics:
  tracking_id: UA-141207776-1 # <app_id>

# ---------------------------------------------------------------
# Search Services
# See: https://theme-next.js.org/docs/third-party-services/search-services
# ---------------------------------------------------------------

# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true

# ---------------------------------------------------------------
# Tags Settings
# See: https://theme-next.js.org/docs/tag-plugins/
# ---------------------------------------------------------------

note:
  icons: true

# ---------------------------------------------------------------
# Animation Settings
# ---------------------------------------------------------------

motion:
  enable: false