# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 纯粹
subtitle: '风卷过的起点'
description: '爱美食/纪录片/夜猫子'
keywords: [班班, Leirock, Hexo, blog, 博客, 经济学, economics]
author: 班班
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://blog.dlzhang.com
root: /
permalink: /post/:pid/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: timeline
category_dir: ''
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 404.html

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: true
  tab_replace: true
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 5
  order_by: -date

# Category & Tag
default_category: life
category_map:
  碎碎念: life
  观察者: viewpoint
  书影音: media
  笔记本: note
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Minifier & Optimization plugin
## See: https://github.com/chenzhutian/hexo-all-minifier
all_minifier: true
html_minifier:
  silent: true
css_minifier:
  silent: true
js_minifier:
  silent: true
image_minifier:
  enable: false

# Hexo Server
server:
  port: 4000
  ip: 127.0.0.1

# Waline
# For more information: https://waline.js.org
waline:
  enable: true
  libUrl: https://lib.baomitu.com/waline/latest/Waline.min.js
  serverURL: https://waline.dlzhang.com # Waline server address url
  avatar: '' # Gravatar style
  login: disable
  meta: [nick, mail, link] # Custom comment header
  requiredMeta: [nick, mail] # Set required fields: [nick] | [nick, mail]
  pageSize: 5 # Pagination size
  visitor: false # Article reading statistic
  comment_count: true  # If false, comment count will only be displayed in post page, not in home page
  copyright: false
  dark: auto
  emoji:  [
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/weibo',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tw-emoji',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/qq',
  ]
  locale:
    placeholder: 在这里分享你的观点与想法，评论通过审核后才会显示。昵称、邮箱必填，回复通过邮件提醒。 # Comment box placeholder
    admin: 博主
    nick: 昵称*
    mail: 邮箱*
    link: 网址
    #login: 管理

# hexo-renderer-markdown-it
# For more information: https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration
markdown:
  langPrefix: 'language-'
  plugins:
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup

#########################
##### 以下插件设置停用 #####
#########################

# Replace any theme file in layout folder to a custom file.
# For more information: https://github.com/jiangtj/hexo-extend-theme
theme_plus:
  views:
    - path: 'page.njk'
      file: 'custom/page.njk'
    - path: 'archive.njk'
      file: 'custom/archive.njk'