# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See: https://theme-next.js.org/docs/theme-settings/
# ---------------------------------------------------------------

# Remove unnecessary files after hexo generate.
minify: true

# Define custom file paths.
# Create your custom files in site directory `source/_data` and uncomment needed files below.
custom_file_path:
  #head: source/_data/head.njk
  #header: source/_data/header.njk
  #sidebar: source/_data/sidebar.njk
  #postMeta: source/_data/post-meta.njk
  postBodyEnd: source/_data/post-body-end.njk
  #footer: source/_data/footer.njk
  #bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
  mixin: source/_data/mixins.styl
  style: source/_data/styles.styl

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

scheme: Gemini
darkmode: true
# Color style: Day of Mourning
gray: false

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

favicon:
  small: ./images/favicon-16x16-next.png
  medium: ./images/favicon-32x32-next.png
  apple_touch_icon: ./images/apple-touch-icon-next.png
  safari_pinned_tab: ./images/safari-pinned-tab-next.svg

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || fas fa-home
  overview: 
    default: /overview/ || fas fa-archive
    tags: tags/ || fas fa-tags
    timeline: timeline/ || fas fa-stream
  about: /about/ || fas fa-location-arrow
  friends: friends/ || fas fa-heart

# ---------------------------------------------------------------
# Sidebar Settings
# See: https://theme-next.js.org/docs/theme-settings/sidebar
# ---------------------------------------------------------------

# Sidebar Avatar
avatar:
  url: /images/avatar.gif
  rounded: true

# Posts / Categories / Tags in sidebar.
site_state: false

social:
  微博: https://weibo.com || fab fa-weibo
  GitHub: https://github.com || fab fa-github
  RSS: /atom.xml || fas fa-rss

social_icons:
  icons_only: true

toc:
  # Automatically add list number to toc.
  number: false

# ---------------------------------------------------------------
# Footer Settings
# See: https://theme-next.js.org/docs/theme-settings/footer
# ---------------------------------------------------------------

footer:
  since: 2016

  # Icon between year and copyright info.
  icon:
    name: fas fa-heart
    animated: true
    color: "#f06292"

  # Powered by Hexo & NexT
  powered: true

# ---------------------------------------------------------------
# Post Settings
# See: https://theme-next.js.org/docs/theme-settings/posts
# ---------------------------------------------------------------

# Read more button
read_more_btn: false

# Post meta display settings
post_meta:
  updated_at:
    enable: false

# Post wordcount display settings
# Dependencies: https://github.com/next-theme/hexo-word-counter
symbols_count_time:
  separated_meta: false

# Use icon instead of the symbol # to indicate the tag at the bottom of the post
tag_icon: true

# ---------------------------------------------------------------
# Misc Theme Settings
# See: https://theme-next.js.org/docs/theme-settings/miscellaneous
# ---------------------------------------------------------------

# Preconnect CDN for fonts and plugins.
preconnect: true

# Android Chrome header panel color ($brand-bg / $headband-bg => $black-deep).
android_chrome_color: "#6c599f"

codeblock:
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: tomorrow
    dark: tomorrow-night
  copy_button:
    enable: true
    style: mac

back2top:
  scrollpercent: true

# ---------------------------------------------------------------
# Font Settings
# ---------------------------------------------------------------

font:
  enable: true
  global:
    family: EB Garamond, Noto Serif SC
  title:
    family: Long Cang
    size: 2
  headings:
    size: 1.48

# ---------------------------------------------------------------
# SEO Settings
# See: https://theme-next.js.org/docs/theme-settings/seo
# ---------------------------------------------------------------

#google_site_verification:
#baidu_site_verification:

# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# See: https://theme-next.js.org/docs/third-party-services/
# ---------------------------------------------------------------

math:
  mathjax:
    enable: true
pjax: true
fancybox: true
lazyload: true
pangu: true

# ---------------------------------------------------------------
# Statistics and Analytics
# See: https://theme-next.js.org/docs/third-party-services/statistics-and-analytics
# ---------------------------------------------------------------

#google_analytics:
#  tracking_id:

# ---------------------------------------------------------------
# Search Services
# See: https://theme-next.js.org/docs/third-party-services/search-services
# ---------------------------------------------------------------

# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true

# ---------------------------------------------------------------
# Tags Settings
# See: https://theme-next.js.org/docs/tag-plugins/
# ---------------------------------------------------------------

# Note tag (bootstrap callout)
note:
  # Note tag style values:
  #  - simple    bootstrap callout old alert style. Default.
  #  - modern    bootstrap callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  icons: true
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# ---------------------------------------------------------------
# Animation Settings
# ---------------------------------------------------------------

motion:
  enable: false

images: /blog/images
